# Generated by Django 4.1.1 on 2023-01-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Urunler",
            fields=[
                ("barcode", models.IntegerField(primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("stock", models.IntegerField()),
                ("price", models.PositiveIntegerField()),
            ],
        ),
    ]
