# Generated by Django 4.1.1 on 2023-01-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calisanlar",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "fullName",
                    models.CharField(max_length=45, verbose_name="İsim Soyisim"),
                ),
                ("telNo", models.CharField(max_length=11, verbose_name="İletişim No")),
                ("mail", models.CharField(max_length=50, verbose_name="E-posta")),
                ("adress", models.CharField(max_length=100, verbose_name="Adres")),
            ],
        ),
        migrations.AlterField(
            model_name="urunler",
            name="barcode",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Barkod"
            ),
        ),
        migrations.AlterField(
            model_name="urunler",
            name="brand",
            field=models.CharField(max_length=50, verbose_name="Marka"),
        ),
        migrations.AlterField(
            model_name="urunler",
            name="model",
            field=models.CharField(max_length=100, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="urunler",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Fiyat"),
        ),
        migrations.AlterField(
            model_name="urunler",
            name="stock",
            field=models.IntegerField(verbose_name="Stok Sayısı"),
        ),
    ]
