# Generated by Django 4.1.1 on 2023-01-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_calisanlar_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Musteriler",
            fields=[
                (
                    "date",
                    models.DateTimeField(
                        auto_created=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "customerID",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "fullName",
                    models.CharField(max_length=45, verbose_name="Müşteri Adı"),
                ),
                ("telNo", models.CharField(max_length=11, verbose_name="İletişim No")),
                ("adress", models.CharField(max_length=100, verbose_name="Adres")),
            ],
        ),
    ]
