# Generated by Django 4.1.1 on 2023-01-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_musteriler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musteriler",
            name="customerID",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, verbose_name="Müşteri Kimliği"
            ),
        ),
    ]
