# Generated by Django 4.1.1 on 2023-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_musteriler_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musteriler",
            name="customerID",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Müşteri Kimliği"
            ),
        ),
    ]
