# Generated by Django 4.1.1 on 2023-01-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_musteriler_customerid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calisanlar",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="urunler",
            name="barcode",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Barkod"
            ),
        ),
    ]
