# Generated by Django 4.1.1 on 2023-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_alter_calisanlar_id_alter_urunler_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urunler",
            name="price",
            field=models.BigIntegerField(verbose_name="Fiyat"),
        ),
    ]
