# Generated by Django 4.1.1 on 2023-01-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_alter_urunler_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Urunler",
        ),
    ]
