# Generated by Django 4.1.1 on 2023-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_delete_urunler"),
    ]

    operations = [
        migrations.CreateModel(
            name="Urunler",
            fields=[
                (
                    "barcode",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Barkod"
                    ),
                ),
                ("brand", models.CharField(max_length=50, verbose_name="Marka")),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                ("stock", models.IntegerField(verbose_name="Stok Sayısı")),
                ("price", models.BigIntegerField(verbose_name="Fiyat")),
            ],
        ),
    ]
