# Generated by Django 4.1.1 on 2023-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_calisanlar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calisanlar",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="TC"
            ),
        ),
    ]
