# Generated by Django 4.1.1 on 2023-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0014_alter_calisanlar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calisanlar",
            name="telNo",
            field=models.BigIntegerField(max_length=11, verbose_name="İletişim No"),
        ),
    ]
