# Generated by Django 4.1.1 on 2023-01-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0015_alter_calisanlar_telno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tedarikciler",
            fields=[
                ("ted_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "comp_name",
                    models.CharField(max_length=60, verbose_name="Tedarikçi Şirket"),
                ),
                (
                    "tel_no",
                    models.BigIntegerField(max_length=11, verbose_name="İletişim No"),
                ),
                ("mail", models.CharField(max_length=50, verbose_name="E-posta")),
                ("adress", models.CharField(max_length=100, verbose_name="Adres")),
            ],
        ),
    ]
